name: Test Notebooks

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9, "3.10"]

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install nbconvert jupyter
    
    - name: Test notebooks
      run: |
        for notebook in notebooks/*.ipynb; do
          echo "Testing $notebook"
          jupyter nbconvert --to notebook --execute --inplace "$notebook"
        done
    
    - name: Check for notebook execution errors
      run: |
        echo "All notebooks executed successfully!"